/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BookingItemSrvObjectPageObjectPage journey");

        opaTest("Navigate to BookingItemSrvObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheBookingSrvList.onFilterBar().iExecuteSearch();

            Then.onTheBookingSrvList.onTable().iCheckRows();
            When.onTheBookingSrvList.onTable().iPressRow(0);

            Then.onTheBookingSrvObjectPage.iSeeThisPage();
            Then.onTheBookingSrvObjectPage.onTable({ property: "_bookingItem" }).iCheckRows();
            When.onTheBookingSrvObjectPage.onTable({ property: "_bookingItem" }).iPressRow(0);

            Then.onTheBookingItemSrvObjectPage.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBookingItemSrvObjectPage.iCheckSection({ section: "ItemData" });
            Then.onTheBookingItemSrvObjectPage.onForm({ section: "ItemData" }).iCheckField({ property: "ItemId" });
            Then.onTheBookingItemSrvObjectPage.onForm({ section: "ItemData" }).iCheckField({ property: "ProductId" });
            Then.onTheBookingItemSrvObjectPage.onForm({ section: "ItemData" }).iCheckField({ property: "Quantity" });
            Then.onTheBookingItemSrvObjectPage.onForm({ section: "ItemData" }).iCheckField({ property: "ItemPrice" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});