/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BookingSrvObjectPageObjectPage journey");

        opaTest("Navigate to BookingSrvObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheBookingSrvList.onFilterBar().iExecuteSearch();

            Then.onTheBookingSrvList.onTable().iCheckRows();
            When.onTheBookingSrvList.onTable().iPressRow(0);

            Then.onTheBookingSrvObjectPage.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheBookingSrvObjectPage.onHeader().iCheckHeaderFacet({ facetId: "RatingHdr" });
            Then.onTheBookingSrvObjectPage.onHeader().iCheckHeaderFacet({ facetId: "ProgressHdr" });
            Then.onTheBookingSrvObjectPage.onHeader().iCheckHeaderFacet({ facetId: "PriceHdr" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBookingSrvObjectPage.iCheckNumberOfSections(2);
            When.onTheBookingSrvObjectPage.iPressSectionIconTabFilterButton("General");
            Then.onTheBookingSrvObjectPage.iCheckSection({ section: "General" });
            When.onTheBookingSrvObjectPage.iPressSectionIconTabFilterButton("Items");
            Then.onTheBookingSrvObjectPage.iCheckSection({ section: "Items" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});