/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BookingSrvListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheBookingSrvList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheBookingSrvList.onFilterBar().iCheckFilterField("Customer");
            Then.onTheBookingSrvList.onFilterBar().iCheckFilterField("Booking Date");
            Then.onTheBookingSrvList.onFilterBar().iCheckFilterField("Status");
            Then.onTheBookingSrvList.onFilterBar().iCheckFilterField("City");
            Then.onTheBookingSrvList.onFilterBar().iCheckFilterField("Confirmed");
            Then.onTheBookingSrvList.onFilterBar().iCheckFilterField("Priority");
        });

        opaTest("Add semantic key properties to filter bar", function (Given, When, Then) {
            Then.onTheBookingSrvList.onFilterBar().iOpenFilterAdaptation();
            When.onTheBookingSrvList.onFilterBar().iAddAdaptationFilterField("Booking ID");
            Then.onTheBookingSrvList.onFilterBar().iConfirmFilterAdaptation();
            Then.onTheBookingSrvList.onFilterBar().iCheckFilterField("Booking ID");
            // Then.onTheBookingSrvList.onFilterBar().iChangeFilterField("Booking ID");
            // Then.onTheBookingSrvList.onFilterBar().iExecuteSearch();
            // Then.onTheBookingSrvList.onTable().iCheckRows();
            // Then.onTheBookingSrvList.onTable().iSelectRows(0);
            // Then.onTheBookingSrvList.onTable().iCheckAction("<Action Name>", { enabled: true });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheBookingSrvList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheBookingSrvList.onFilterBar().iExecuteSearch();
        //     Then.onTheBookingSrvList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheBookingSrvList.onTable().iCheckColumns(undefined, {"6":{"header":"Price Chart"},"8":{"header":"Rating"},"9":{"header":"Completion"},"BookingId":{"header":"Booking ID"},"CustomerId":{"header":"Customer"},"BookingDate":{"header":"Booking Date"},"OverallStatus":{"header":"Status"},"Priority":{"header":"Priority"},"TotalPrice":{"header":"Total Price"},"ConfirmFlag":{"header":"Confirmed"},"Description":{"header":"Description"},"CustomerName":{"header":"Contact"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheBookingSrvList.onFilterBar().iExecuteSearch();
            
            Then.onTheBookingSrvList.onTable().iCheckRows();

            When.onTheBookingSrvList.onTable().iPressRow(0);
            Then.onTheBookingSrvObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});